// 技術タグデータ（カテゴリごと）
export const tagData: Record<string, { id: number; title: string }[]> = {
  "AI・機械学習": [
    { id: 1, title: "生成 AI の基礎概念と活用事例を体系的に学ぶ" },
    { id: 2, title: "LLM を用いたアプリ開発の実践ワークショップ" },
    { id: 3, title: "AI 駆動開発フローを理解しプロジェクトに適用する" },
    { id: 4, title: "効果的なプロンプト設計と評価手法をハンズオンで習得" },
    { id: 5, title: "LangChain を使ったチャットボット構築の実例解説" },
    { id: 6, title: "RAG パターンによる社内ドキュメント検索を構築" },
    { id: 7, title: "MLOps パイプラインの設計と継続的学習の運用方法" },
    { id: 8, title: "AutoML ツール比較と最適な選定ポイントの紹介" },
    { id: 9, title: "現場データを使った前処理・特徴量エンジニアリング" },
    { id: 10, title: "「機械学習入門」モデル作成から評価までの一連演習" },
    { id: 11, title: "CNN/RNN など DL 基礎アルゴリズムの実装体験" },
    { id: 12, title: "画像認識 AI を Vision API と自前モデルで比較検証" },
    { id: 13, title: "音声認識・合成 AI を用いたアプリケーション構築" },
    { id: 14, title: "エッジ AI デバイス上でのモデル最適化と推論デモ" },
    { id: 15, title: "強化学習を用いたゲーム AI チュートリアル" },
  ],
  "Web・モバイル開発": [
    { id: 19, title: "TypeScript 型システムを活かした大規模開発手法" },
    { id: 20, title: "Next.js 14 の新機能と App Router 移行ガイド" },
    { id: 21, title: "React 最新 Hooks パターンとパフォーマンス最適化" },
    { id: 22, title: "Vue 3 Composition API で設計する大規模 SPA" },
    { id: 23, title: "SvelteKit を用いた軽量フルスタック開発体験" },
    { id: 24, title: "Flutter×Firebase でマルチプラットフォームアプリ" },
    { id: 25, title: "Kotlin で学ぶモダン Android 開発実践コース" },
    { id: 26, title: "SwiftUI と Combine による iOS アプリ開発入門" },
    { id: 80, title: "UX リサーチ手法とユーザーテスト設計" },
    { id: 81, title: "デザインシステム構築と Figma 運用ベストプラクティス" },
    { id: 82, title: "Figma Auto Layout とコンポーネント上級編" },
  ],
  "バックエンド・クラウド基盤": [
    { id: 17, title: "Go 言語による高並行サーバー実装ハンズオン" },
    { id: 31, title: "GraphQL サーバー設計とクエリ最適化手法" },
    { id: 32, title: "gRPC と ProtocolBuffers による高速 API 通信" },
    { id: 33, title: "RESTful API 設計原則と OpenAPI ドキュメント自動生成" },
    { id: 41, title: "Serverless アーキテクチャで学ぶコスト最適化" },
    { id: 42, title: "AWS 認定試験対策と実務スキルマッピング" },
    { id: 43, title: "GCP 基本サービスと Anthos を活かした運用例" },
    { id: 44, title: "Azure DevOps を用いた CI/CD パイプライン構築" },
    { id: 45, title: "Kubernetes クラスタ設計と Helm 導入ハンズオン" },
    { id: 46, title: "Istio サービスメッシュでのトラフィック管理" },
    { id: 47, title: "Terraform でクラウドインフラをコード化する演習" },
    { id: 48, title: "Pulumi×TypeScript でマルチクラウド IaC 実践" },
    { id: 49, title: "GitHub Actions による自動テスト＆デプロイ設定" },
    { id: 50, title: "高信頼 CI/CD パイプラインと Blue-Green デプロイ" },
    { id: 51, title: "SRE の原則と SLO/SLA 設定ワークショップ" },
    { id: 52, title: "オブザーバビリティ：ログ・メトリクス・トレース統合" },
    { id: 53, title: "Chaos Engineering でシステム耐障害性を検証" },
    { id: 54, title: "FinOps でクラウドコストを最適化する実務手法" },
  ],
  "ソフトウェア設計・開発プラクティス": [
    { id: 16, title: "Python 初心者向け文法と標準ライブラリ速習会" },
    { id: 18, title: "Rust で安全かつ高速な CLI ツールを作る実践" },
    { id: 38, title: "クリーンアーキテクチャで保守性高い設計演習" },
    { id: 39, title: "実践 DDD：ドメインモデル設計から実装まで" },
    { id: 40, title: "マイクロサービス分割戦略とデータ整合性設計" },
    { id: 75, title: "読みやすい設計ドキュメントと ADR の書き方" },
    { id: 76, title: "レガシーコードを段階的にリファクタする戦略" },
    { id: 77, title: "自動テスト設計とテストピラミッド実践" },
    { id: 78, title: "ペアプログラミングとモブプロの効果的な進め方" },
    { id: 79, title: "コードレビュー文化構築とコメント指針" },
    { id: 83, title: "Agile 開発におけるプランニングと振り返り" },
    { id: 84, title: "認定 Scrum Master 試験対策と実例共有" },
  ],
  "ゲーム開発・グラフィックス": [
    { id: 27, title: "C#と Unity で 2D/3D ゲームをゼロから制作" },
    { id: 28, title: "Unreal Engine でフォトリアルゲーム環境構築" },
    { id: 29, title: "Godot Engine 入門とオープンソースゲーム制作" },
    { id: 30, title: "WebGL と Three.js でインタラクティブ 3D 表現" },
  ],
  "セキュリティ・ブロックチェーン": [
    { id: 34, title: "API セキュリティ攻撃例と対策パターン解説" },
    { id: 35, title: "OAuth2.1 フロー実装と SSO 統合ハンズオン" },
    { id: 36, title: "OpenID Connect での ID 連携とトラスト設計" },
    { id: 37, title: "JWT 活用によるステートレス認証システム構築" },
    { id: 55, title: "最新サイバー脅威動向と防御パターン解説" },
    { id: 56, title: "Web アプリ脆弱性診断とペネトレーション実習" },
    { id: 57, title: "Web3 基礎概念と分散アプリ DApp 開発入門" },
    { id: 58, title: "ブロックチェーンスマートコントラクト実装体験" },
    { id: 59, title: "Solidity で ERC-20 トークンを発行するハンズオン" },
    { id: 60, title: "Rust×Solana で高速 DeFi アプリ開発" },
  ],
  "IoT・XR・先進技術": [
    { id: 61, title: "IoT デバイス連携と MQTT プロトコル基礎" },
    { id: 62, title: "Edge デバイス上の AI 推論とネットワーク最適化" },
    { id: 63, title: "AR/VR コンテンツ制作と Unity XR Toolkit 入門" },
    { id: 64, title: "メタバースプラットフォーム活用事例とビジネス展望" },
  ],
  "キャリア・マネジメント": [
    { id: 65, title: "プロダクト思考で価値を届ける要件定義ワーク" },
    { id: 66, title: "PM と開発チームの協調プロセス改善手法" },
    { id: 67, title: "EM 向け 1on1 と組織マネジメント実践" },
    { id: 68, title: "テックリードが行う技術戦略と育成メソッド" },
    { id: 69, title: "キャリアデザイン：将来のビジョン策定ワークショップ" },
    { id: 70, title: "海外テック企業転職のための英語面接対策" },
    { id: 71, title: "フリーランスエンジニア案件獲得と単価交渉術" },
    { id: 93, title: "女性エンジニアが語るキャリアとコミュニティ活動" },
  ],
  "コミュニティ・ソフトスキル": [
    { id: 72, title: "OSS コントリビューション入門と GitHub フロー" },
    { id: 73, title: "技術ブログ・SNS 発信で影響力を高める方法" },
    { id: 74, title: "技術イベント登壇準備と魅力的な資料作成" },
    { id: 85, title: "DevRel 戦略でコミュニティを拡大する" },
    { id: 86, title: "ハッカソンで MVP を作る実践ガイド" },
    { id: 87, title: "もくもく会で集中力を高めるタスク管理術" },
    { id: 88, title: "LT 大会で刺さるプレゼンの作り方" },
    { id: 89, title: "オンラインで学ぶライト勉強会" },
    { id: 90, title: "ハンズオンで新技術を短期習得" },
    { id: 91, title: "オンライン × オフラインのハイブリッド運営ノウハウ" },
    { id: 92, title: "地方コミュニティ立ち上げと運営のコツ" },
    { id: 94, title: "初学者歓迎：ゼロから始めるプログラミング講座" },
    { id: 95, title: "中級者向けスキルアップロードマップ作成" },
    { id: 96, title: "上級者向けアーキテクチャ設計ディスカッション" },
    { id: 97, title: "英語オンリーセッションで国際交流を体験" },
    { id: 98, title: "ネットワーキングで人脈を広げるコツ" },
    { id: 99, title: "懇親会で学びを深めるアイスブレイク術" },
    { id: 100, title: "イベント後フォローアップと学習継続サポート" },
  ],
};
